blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://robertraaijmakers.github.io/com.trashchecker/
    about: Check the documentation for help and guides
  - name: Homey Community Forum
    url: https://community.homey.app/t/app-pro-trashcan-reminder-2-0/114178
    about: Ask questions and discuss with other Homey users
